[package]
name = "test-btleplug"
version = "0.1.0"
authors = ["Viet Le <vietlq85@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.4"
rand = "0.7"
